version: '3'

services:
  # Store data efficiently in encrypted blocks
  database:
    image: restic/rest-server

  # Download videos and print status updates to condole
  queue:
    image: youtube-dl:development
    command: flask run
    working_dir: /work
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=downloader
    volumes:
      - .:/work

  # Download json for url and thumbnail for presentation
  # Maybe alows for selective enqueue since some videos witll be not good
  collection:
    image: ruby
    working_dir: /work
    volumes:
      - .:/work
