version: '3'

services:
  # Store data efficiently in encrypted blocks
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    working_dir: /work
    command: /usr/local/bin/rest-server --no-auth --append-only --path /usr/local/data
    volumes:
      - ./bin:/usr/local/bin
      - /Volumes/y00000001:/work
      - /Volumes/y00000001/nitflix:/usr/local/data


  # Download json for url and thumbnail for presentation
  # Maybe alows for selective enqueue since some videos witll be not good
  collection:
    image: ruby
    working_dir: /work
    volumes:
      - .:/work
      - bundle:/usr/local/bundle
  #   depends_on:
  #     - queue
  # Download videos and print status updates to condole
  thumbnail:
    build:
      context: .
      dockerfile: Dockerfile.youtube-dl
    command: youtube-dl --write-thumbnail "ytsearch:$VIDEO_TITLE"
    working_dir: /work
    environment:
      - COURSE_HREF=${COURSE_HREF}
      - VIDEO_TITLE=${VIDEO_TITLE}
    volumes:
      - thumbnails:/work
  queue:
    build:
      context: .
      dockerfile: Dockerfile.youtube-dl
    command: youtube-dl "ytsearch:$VIDEO_TITLE" --match-filter "channel = 'MIT OpenCourseWare'" --exec 'restic backup {} --tag $COURSE_HREF && rm {}'
    working_dir: /work
    environment:
      - RESTIC_REPOSITORY=rest:http://database:8000
      - RESTIC_PASSWORD=test
      - COURSE_HREF=${COURSE_HREF}
      - VIDEO_TITLE=${VIDEO_TITLE}
    volumes:
      - /Volumes/y00000001:/work
    depends_on:
      - database
  subtitles:
    build:
      context: .
      dockerfile: Dockerfile.youtube-dl
    command: youtube-dl --skip-download --write-auto-sub --sub-lang $LANGUAGES "ytsearch:$VIDEO_TITLE" #--exec 'restic backup {} --tag $COURSE_HREF && rm {}'
    working_dir: /usr/local/work
    environment:
      - LANGUAGES=en,nl,de,ru,es,fr
      - VIDEO_TITLE=${VIDEO_TITLE}
    volumes:
      - subtitles:/usr/local/work

volumes:
  subtitles: {}
  thumbnails: {}
  bundle: {}
